### ISSUE TITLE
Readme.mdで表示されていない画像

### ISSUE THREAD

**Issue by imamurayusuke** [74th/sparrow62-buildguide#4]
こんにちは、プルリクエストを出す方法がわからずissueで失礼します。

34行目と35行目
img/top_choc.jpg→img/v1/top_choc.jpg
img/top_choc2.jpg→img/v1/top_choc2.jpg

150行目
img/choc_v2.jpg→img/v1/choc_v2.jpg

これで画像が表示されると思います。ご確認くださいませ。

**Comment by 74th** [comment]
ご指摘ありがとうございます！助かります。

修正させていただきました。
